### ISSUE TITLE
Feature request: Add SD index. 

### ISSUE THREAD

**Issue by isukrit** [alashkov83/S_Dbw#3]
Please add functionality to get the SD index as well.

**Comment by alashkov83** [comment]
isukrit, I analyzed your decision in detail and came to the conclusion that it was wrong in terms of the choice of the weighting factor. The weight coefficient is necessary when evaluating solutions with a different number of clusters. It is equal not only to the distance between the centroids, but to the distance between the centroids in the case of the maximum number of clusters. It should be calculated once and separately, and then set in the parameters of the SD function. In the next meeting, I fixed it. this. And thank you for your help.
