### ISSUE TITLE
Unable to Import this package 

### ISSUE THREAD

**Issue by TDharm** [alashkov83/S_Dbw#7]
Unable to import this package,always get this error:
>  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'S_Dbw'

Python version: 3.6.6 (Anaconda)
All dependencies are already satisfied as follows:

Requirement already satisfied: S_Dbw in /root/anaconda3/lib/python3.6/site-packages (0.4.0)
Requirement already satisfied: scipy in /root/anaconda3/lib/python3.6/site-packages (from S_Dbw) (1.0.0)

**Comment by alashkov83** [comment]
> from s_dbw import S_Dbw

Are you using this command?
